apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moodify-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "4.251.168.14.nip.io" # replace with your actual public IP or use nip.io as shown
      http:
        paths:
          - path: /api/audio
            pathType: Prefix
            backend:
              service:
                name: audioservice
                port:
                  number: 8080
          - path: /api/playlist
            pathType: Prefix
            backend:
              service:
                name: playlistservice
                port:
                  number: 8080
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 8080
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: userservice
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
