# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moodify-ingress
  namespace: moodify
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - "4.251.168.14.nip.io"
      secretName: moodify-tls
  rules:
    - host: "4.251.168.14.nip.io"
      http:
        paths:
          - path: /api/Audio
            pathType: Prefix
            backend:
              service:
                name: audioservice
                port:
                  number: 8080
          - path: /api/Playlist
            pathType: Prefix
            backend:
              service:
                name: playlistservice
                port:
                  number: 8080
          - path: /api/Auth
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 8080
          - path: /api/User
            pathType: Prefix
            backend:
              service:
                name: userservice
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
